name: ci
permissions:
  checks: write
  statuses: write
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ci-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19", "1.20", "1.21", "1.22", "1.x"]
    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4
      - name: Use go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go mod download
      - run: go build .
      - run: go test -v

      - name: Report Status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              state: 'success',
              description: 'CI tests passed successfully',
              context: 'CI Status'
            });
